name: Frontend CI → Deploy under /smarttrack

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: eu-west-3
  CLOUDFRONT_DISTRIBUTION_ID: E3J5TDDPPQXI3U

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      # build avec base-href pour /smarttrack
      - run: npm run build -- --configuration production --base-href /smarttrack/

      # déployer dans S3 sous /smarttrack/
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/smarttrack s3://${{ env.S3_BUCKET }}/smarttrack \
            --delete --cache-control "max-age=31536000"

      # invalider CloudFront
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/smarttrack/*"
