name: Deploy Angular to S3 (/smarttrack)

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      # 🔹 Build Angular avec base-href /smarttrack/
      - name: Build Angular app
        run: npm run build -- --configuration production

      # 🔹 Sync vers S3 dans le sous-dossier /smarttrack/
      - name: Sync files to S3
        run: |
          aws s3 sync dist/smarttrack-ui s3://${{ secrets.S3_BUCKET }} \
            --delete --cache-control "max-age=31536000"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # 🔹 Config AWS (pour CloudFront ensuite)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      # 🔹 Invalidation CloudFront uniquement sur /smarttrack/*
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3J5TDDPPQXI3U \
            --paths "/smarttrack/*"